version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: greenreceipt-db
    environment:
      POSTGRES_DB: greenreceipt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
